# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sukrutrahulbidwai/Downloads/CPP-Memory-Leak-Detection-Lib-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sukrutrahulbidwai/Downloads/CPP-Memory-Leak-Detection-Lib-main/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sukrutrahulbidwai/Downloads/CPP-Memory-Leak-Detection-Lib-main/build/CMakeFiles /Users/sukrutrahulbidwai/Downloads/CPP-Memory-Leak-Detection-Lib-main/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sukrutrahulbidwai/Downloads/CPP-Memory-Leak-Detection-Lib-main/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mld_library

# Build rule for target.
mld_library: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mld_library
.PHONY : mld_library

# fast build rule for target.
mld_library/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mld_library.dir/build.make CMakeFiles/mld_library.dir/build
.PHONY : mld_library/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/LeakDetector.o: src/LeakDetector.cpp.o
.PHONY : src/LeakDetector.o

# target to build an object file
src/LeakDetector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mld_library.dir/build.make CMakeFiles/mld_library.dir/src/LeakDetector.cpp.o
.PHONY : src/LeakDetector.cpp.o

src/LeakDetector.i: src/LeakDetector.cpp.i
.PHONY : src/LeakDetector.i

# target to preprocess a source file
src/LeakDetector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mld_library.dir/build.make CMakeFiles/mld_library.dir/src/LeakDetector.cpp.i
.PHONY : src/LeakDetector.cpp.i

src/LeakDetector.s: src/LeakDetector.cpp.s
.PHONY : src/LeakDetector.s

# target to generate assembly for a file
src/LeakDetector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mld_library.dir/build.make CMakeFiles/mld_library.dir/src/LeakDetector.cpp.s
.PHONY : src/LeakDetector.cpp.s

src/ReferenceTracker.o: src/ReferenceTracker.cpp.o
.PHONY : src/ReferenceTracker.o

# target to build an object file
src/ReferenceTracker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mld_library.dir/build.make CMakeFiles/mld_library.dir/src/ReferenceTracker.cpp.o
.PHONY : src/ReferenceTracker.cpp.o

src/ReferenceTracker.i: src/ReferenceTracker.cpp.i
.PHONY : src/ReferenceTracker.i

# target to preprocess a source file
src/ReferenceTracker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mld_library.dir/build.make CMakeFiles/mld_library.dir/src/ReferenceTracker.cpp.i
.PHONY : src/ReferenceTracker.cpp.i

src/ReferenceTracker.s: src/ReferenceTracker.cpp.s
.PHONY : src/ReferenceTracker.s

# target to generate assembly for a file
src/ReferenceTracker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mld_library.dir/build.make CMakeFiles/mld_library.dir/src/ReferenceTracker.cpp.s
.PHONY : src/ReferenceTracker.cpp.s

src/ResourceManager.o: src/ResourceManager.cpp.o
.PHONY : src/ResourceManager.o

# target to build an object file
src/ResourceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mld_library.dir/build.make CMakeFiles/mld_library.dir/src/ResourceManager.cpp.o
.PHONY : src/ResourceManager.cpp.o

src/ResourceManager.i: src/ResourceManager.cpp.i
.PHONY : src/ResourceManager.i

# target to preprocess a source file
src/ResourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mld_library.dir/build.make CMakeFiles/mld_library.dir/src/ResourceManager.cpp.i
.PHONY : src/ResourceManager.cpp.i

src/ResourceManager.s: src/ResourceManager.cpp.s
.PHONY : src/ResourceManager.s

# target to generate assembly for a file
src/ResourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mld_library.dir/build.make CMakeFiles/mld_library.dir/src/ResourceManager.cpp.s
.PHONY : src/ResourceManager.cpp.s

tests/ReferenceTrackerTest.o: tests/ReferenceTrackerTest.cpp.o
.PHONY : tests/ReferenceTrackerTest.o

# target to build an object file
tests/ReferenceTrackerTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mld_library.dir/build.make CMakeFiles/mld_library.dir/tests/ReferenceTrackerTest.cpp.o
.PHONY : tests/ReferenceTrackerTest.cpp.o

tests/ReferenceTrackerTest.i: tests/ReferenceTrackerTest.cpp.i
.PHONY : tests/ReferenceTrackerTest.i

# target to preprocess a source file
tests/ReferenceTrackerTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mld_library.dir/build.make CMakeFiles/mld_library.dir/tests/ReferenceTrackerTest.cpp.i
.PHONY : tests/ReferenceTrackerTest.cpp.i

tests/ReferenceTrackerTest.s: tests/ReferenceTrackerTest.cpp.s
.PHONY : tests/ReferenceTrackerTest.s

# target to generate assembly for a file
tests/ReferenceTrackerTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mld_library.dir/build.make CMakeFiles/mld_library.dir/tests/ReferenceTrackerTest.cpp.s
.PHONY : tests/ReferenceTrackerTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... mld_library"
	@echo "... src/LeakDetector.o"
	@echo "... src/LeakDetector.i"
	@echo "... src/LeakDetector.s"
	@echo "... src/ReferenceTracker.o"
	@echo "... src/ReferenceTracker.i"
	@echo "... src/ReferenceTracker.s"
	@echo "... src/ResourceManager.o"
	@echo "... src/ResourceManager.i"
	@echo "... src/ResourceManager.s"
	@echo "... tests/ReferenceTrackerTest.o"
	@echo "... tests/ReferenceTrackerTest.i"
	@echo "... tests/ReferenceTrackerTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

